"use client";
import React, { useEffect, useState } from "react";
import "./globals.css";
import Header from "./Header";
import { AuthContextProvider } from "@/context/store";
import { useAuthContext } from "@/context/store";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const { userData } = useAuthContext();
  return (
    <html lang="en">
      <head></head>
      <body>
        {userData && <Header />}
        <AuthContextProvider>{children}</AuthContextProvider>
      </body>
    </html>
  );
}
