"use client";
import React, { useEffect, useState } from "react";
import "./globals.css";
import Header from "./Header";
import { GlobalContextProvider, useGlobalContext } from "@/context/store";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { userData } = useGlobalContext();
  return (
    <html lang="en">
      <head></head>
      <body>
        {userData[0] && <Header />}
        <GlobalContextProvider>{children}</GlobalContextProvider>
      </body>
    </html>
  );
}
