"use client";
import React, { useEffect, useState } from "react";
import "./globals.css";
import Header from "./Header";
import Head from "next/head";
import Providers from "../components/Providers";
import { usePathname } from "next/navigation";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, location }) {
  const [innerWidth, setInnerWidth] = useState(0);
  const [showNav, setShowNav] = useState(false);
  const pathName = usePathname();

  useEffect(() => {
    if (typeof window !== "undefined") {
      setInnerWidth(window.outerWidth);
      if (window.outerWidth > 640) setShowNav(true);
      setShowNav(JSON.parse(localStorage.getItem("mobile")));
    }
  }, []);

  return (
    <html lang="en">
      <Head>
        <link rel="icon" type="image/x-icon" href="/favicon.ico" />
      </Head>
      <body>
        <Toaster position="top-center" reverseOrder={false} />
        <Providers>
          <div className="flex h-screen overflow-hidden">
            {pathName !== "/login" && (
              <div className={`${showNav ? "w-[300px]" : "w-[100px]"}`}>
                <Header
                  showNav={showNav}
                  setShowNav={setShowNav}
                  innerWidth={innerWidth}
                />
              </div>
            )}

            <div className="w-screen flex-col justify-center items-center">
              {children}
            </div>
            {/* main content */}
          </div>
        </Providers>
      </body>
    </html>
  );
}
