"use client";
import React, { useEffect, useState } from "react";
import "./globals.css";
import Header from "./Header";
import Providers from "@/components/Providers";
import { usePathname } from "next/navigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, location }) {
  const [innerWidth, setInnerWidth] = useState(0);
  const [showNav, setShowNav] = useState(false);
  const pathName = usePathname();

  useEffect(() => {
    if (typeof window !== "undefined") {
      setInnerWidth(window?.innerWidth);
      if (window.innerWidth > 640) setShowNav(true);
    }
  }, []);

  return (
    <html lang="en">
      {/* <Head>
        <meta name="robots" content="noindex" />
      </Head> */}
      <body>
        <Providers>
          <div className="flex h-screen ">
            {pathName !== "/login" && (
              <div className={`${showNav ? "w-[300px]" : "w-[100px]"}`}>
                <Header
                  showNav={showNav}
                  setShowNav={setShowNav}
                  innerWidth={innerWidth}
                />
              </div>
            )}

            <div className="w-screen flex-col justify-center items-center">
              {children}
            </div>
            {/* main content */}
          </div>
        </Providers>
      </body>
    </html>
  );
}
